app:
  rabbitmq:
    queue01: SBMTEST
    queue02: SBMFCR
    queue03: SBMENGINE
    exchange: OMX-Exchange

spring:
  rabbitmq:
#    host: sbmpm-rabbitmq-ha.sbmpm.svc
#    port: 5672
    addresses: sbmpm-rabbitmq-ha.sbmpm.svc:5672
    username: snmpAlarm
    password: snmpAlarm
