apiVersion: v1
kind: Service
metadata:
  name: sbm-rabbitmq-client-dev
  labels:
    app: sbm-rabbitmq-client
    env: "dev"
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: sbm-rabbitmq-client
    env: "dev"
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sbm-rabbitmq-client-dev
  labels:
    app: sbm-rabbitmq-client
    version: "1.0"
    env: "dev"
spec:
  replicas: 1
  serviceName: sbm-rabbitmq-client-dev
  selector:
    matchLabels:
      app: sbm-rabbitmq-client
      env: "dev"
  template:
    metadata:
      labels:
        app: sbm-rabbitmq-client
        env: "dev"
    spec:
      containers:
        - name: sbm-rabbitmq-client-dev
          image: reghbpr01.dc1.true.th/sbmrbt/dev/sbm-rabbitmq-client:1.0
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "Asia/Bangkok"
            - name: ZONE
              value: "dev"
            - name: ENV
              value: "dev"
            - name: APP_ENV
              value: "dev"
            - name: SERVICE_NAME
              value: "sbmcrbt"

          resources:
            requests:
              memory: "10Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"

      imagePullSecrets:
        - name: reghbpr01

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sbm-rabbitmq-client-dev
  labels:
    app: sbm-rabbitmq-client
    env: "dev"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
spec:
  rules:
    - host: sbm-rabbitmq-client-dev.sbmrbt.tyb.rft
      http:
        paths:
          - backend:
              serviceName: sbm-rabbitmq-client-dev
              servicePort: 80
            path: /